# Generated by Django 4.2.11 on 2024-03-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundcloud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracks',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
