# Generated by Django 4.2.8 on 2024-04-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundcloud', '0004_like_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracks',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
