# Generated by Django 4.2.8 on 2024-04-30 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soundcloud', '0005_tracks_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracks',
            name='duration',
        ),
    ]
