# Generated by Django 4.2.8 on 2024-05-02 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundcloud', '0006_remove_tracks_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='moment',
            field=models.IntegerField(default=0),
        ),
    ]
