# Generated by Django 4.2.8 on 2024-05-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundcloud', '0007_comment_moment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m'),
        ),
    ]
