# Generated by Django 4.2.8 on 2024-05-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundcloud', '0008_alter_tracks_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
