# Generated by Django 4.2.8 on 2024-05-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundcloud', '0009_alter_genre_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlisttracks',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playlisttracks',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
