# Generated by Django 4.2.8 on 2024-05-10 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soundcloud', '0010_playlisttracks_status_playlisttracks_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlisttracks',
            name='status',
        ),
        migrations.RemoveField(
            model_name='playlisttracks',
            name='title',
        ),
    ]
